version: '3.4'
#networks:
    #default:
        #external:
            #name: jh-interview-test
services:
  redditscraper.poller:
    image: ${DOCKER_REGISTRY-}redditscraperpoller
    build:
      context: .
      dockerfile: RedditScraper.Poller/Dockerfile
      